### PR TITLE
fixed update service methods and implemented cucumber tests

### LINKED ISSUE #95: Fix update methods to accept only parameters that should be updated
Fix service class update methods

### PR DESCRIPTION
**Pull request by susanmatuszewski**
# Summary

- changed update methods to allow for null arguments, this way only necessary fields are updated
- added more cucumber tests for admin and student
- fixed bug with set and list pointers

## Test Plan

mvn test, integration tests and cucumber tests

## Related Issues

closes #95, part of #54

### CODE REVIEW

File: Backend/src/main/java/ca/mcgill/cooperator/service/EmployerReportService.java [hunk 1]
```diff
@@ -169,50 +166,58 @@ public EmployerReport updateEmployerReport(
...
+        if (c != null) {
+            boolean coopContains = false;
+
+            Set<EmployerReport> coopReports = new HashSet<EmployerReport>();
+            coopReports.addAll(c.getEmployerReports());
+            for (EmployerReport coopEmployerReport : coopReports) {
+                if (coopEmployerReport.getId() == er.getId()) {
+                    coopReports.remove(coopEmployerReport);
+                    coopReports.add(er);
+                    coopContains = true;
```
Comment (kraglalbert) [inline Backend/src/main/java/ca/mcgill/cooperator/service/EmployerReportService.java]: Same thing here, you can break out of the loop once you find the right co-op

File: Backend/src/main/java/ca/mcgill/cooperator/service/EmployerReportService.java [hunk 2]
```diff
@@ -169,50 +166,58 @@ public EmployerReport updateEmployerReport(
...
+        if (ec != null) {
+            boolean employerContains = false;
+
+            Set<EmployerReport> employerReports = new HashSet<EmployerReport>();
+            employerReports.addAll(c.getEmployerReports());
+            for (EmployerReport employerReport : employerReports) {
+                if (employerReport.getId() == er.getId()) {
+                    employerReports.remove(employerReport);
+                    employerReports.add(er);
+                    employerContains = true;
```
Comment (kraglalbert) [inline Backend/src/main/java/ca/mcgill/cooperator/service/EmployerReportService.java]: And here too

File: Backend/src/main/java/ca/mcgill/cooperator/service/NotificationService.java [hunk 3]
```diff
@@ -164,8 +172,10 @@ public Notification updateNotification(
         boolean sender_contains = false;
```
Comment (kraglalbert) [inline Backend/src/main/java/ca/mcgill/cooperator/service/NotificationService.java]: nit: change variable names to camelCase

File: Backend/src/test/java/ca/mcgill/cooperator/controller/StudentReportControllerIT.java [hunk 4]
```diff
@@ -85,5 +99,64 @@ public void testStudentReportFlow() throws Exception {
...
+                MockMvcRequestBuilders.multipart("/student-reports/" + returnedReport.getId());
+        builder.with(
+                new RequestPostProcessor() {
+                    @Override
+                    public MockHttpServletRequest postProcessRequest(
+                            MockHttpServletRequest request) {
+                        request.setMethod("PUT");
+                        return request;
+                    }
+                });
```
Comment (kraglalbert) [inline Backend/src/test/java/ca/mcgill/cooperator/controller/StudentReportControllerIT.java]: 😮

File: Backend/src/main/java/ca/mcgill/cooperator/controller/StudentReportController.java [hunk 5]
```diff
@@ -105,26 +108,27 @@ public StudentReportDto createStudentReport(
     }
 
     /**
-     * Updates a StudentReport
+     * Updates a StudentReport, put not the actual contents of report
```
[the remark this answers is not in the document]
Comment (susanmatuszewski) [reply Backend/src/main/java/ca/mcgill/cooperator/controller/StudentReportController.java]: oh oops old comment, need to delete that anyways

File: Backend/src/main/java/ca/mcgill/cooperator/controller/StudentReportController.java [hunk 6]
```diff
@@ -108,23 +111,24 @@ public StudentReportDto createStudentReport(
      * Updates a StudentReport
      *
      * @param reportId
-     * @param file
      * @param status
      * @param title
      * @param rsDtos
      * @param coopId
      * @return the updated StudentReport
```
Comment (kraglalbert) [inline Backend/src/main/java/ca/mcgill/cooperator/controller/StudentReportController.java]: Update params to match what the method takes in

File: Backend/src/main/java/ca/mcgill/cooperator/service/AdminService.java [hunk 7]
```diff
@@ -115,32 +115,44 @@ public Admin updateAdmin(
...
+        }
+
+        /*if (sentNotifications != null) {
+            for (Notification n : sentNotifications) {
+                n.setSender(a);
+                notificationRepository.save(n);
+            }
+
+            a.setSentNotifications(sentNotifications);
+        }*/
```
Comment (kraglalbert) [inline Backend/src/main/java/ca/mcgill/cooperator/service/AdminService.java]: Delete commented out code

File: Backend/src/main/java/ca/mcgill/cooperator/service/CompanyService.java [hunk 8]
```diff
@@ -165,41 +159,47 @@ public Company updateCompany(
...
+        if (region == null) {
+            region = c.getRegion();
+        }
+        if (country == null) {
+            country = c.getCountry();
+        }
 
-        companyRepository.save(c);
+        if (companyExists(name, city, region, country)) {
+            String error_message = "Company with this name and location already exists!";
```
Comment (kraglalbert) [inline Backend/src/main/java/ca/mcgill/cooperator/service/CompanyService.java]: nit: should be camelCase (`errorMessage`)

File: Backend/src/main/java/ca/mcgill/cooperator/service/EmployerContactService.java [hunk 9]
```diff
@@ -151,53 +145,48 @@ public EmployerContact updateEmployerContact(
...
-        ec.setEmployerReports(employerReports);
-        ec.setCoopDetails(coopDetails);
-        ec.setCompany(company);
-
-        employerContactRepository.save(ec);
-
-        for (EmployerReport er : employerReports) {
-            er.setEmployerContact(ec);
-            employerReportRepository.save(er);
+        if (firstName != null && firstName.trim().length() > 0) {
```
Comment (kraglalbert) [inline Backend/src/main/java/ca/mcgill/cooperator/service/EmployerContactService.java]: I think you can delete the check for `length() > 0` since we know that it's not 0 if we've hit this if-condition

File: Backend/src/main/java/ca/mcgill/cooperator/service/StudentService.java [hunk 10]
```diff
@@ -201,47 +159,41 @@ public Student updateStudent(
...
-            notif.setStudent(s);
-            notificationRepository.save(notif);
+        if (firstName != null && firstName.trim().length() > 0) {
+            s.setFirstName(firstName.trim());
         }
-
-        for (Coop coop : coops) {
-            coop.setStudent(s);
-            coopRepository.save(coop);
+        if (lastName != null && lastName.trim().length() > 0) {
```
Comment (kraglalbert) [inline Backend/src/main/java/ca/mcgill/cooperator/service/StudentService.java]: Same comment here for the length check

File: Backend/src/test/java/ca/mcgill/cooperator/service/CooperatorServiceNotificationTests.java [hunk 11]
```diff
@@ -54,6 +54,11 @@ public void testCreateNotification() {
         }
 
         assertEquals(1, notificationService.getAllNotifications().size());
+        student = studentService.getStudentById(student.getId());
+        assertEquals("Hello", ((Notification)student.getNotifications().toArray()[0]).getTitle());
```
Comment (kraglalbert) [inline Backend/src/test/java/ca/mcgill/cooperator/service/CooperatorServiceNotificationTests.java]: Why the cast to Notification?

Comment (susanmatuszewski) [reply Backend/src/test/java/ca/mcgill/cooperator/service/CooperatorServiceNotificationTests.java]: because toArray() from a set returns an array of object so you need to cast

File: Backend/src/main/java/ca/mcgill/cooperator/service/EmployerContactService.java (hunk 9 above)
Comment (susanmatuszewski) [reply Backend/src/main/java/ca/mcgill/cooperator/service/EmployerContactService.java]: yes
